// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ToDoEFDB.Context;

namespace ToDoDAL.Migrations
{
    [DbContext(typeof(ToDoAppContext))]
    partial class ToDoAppContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ToDoApp.Models.RoleItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("RoleItem");
                });

            modelBuilder.Entity("ToDoApp.Models.ToDoItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.Property<int?>("ToDoListItemId");

                    b.HasKey("Id");

                    b.HasIndex("ToDoListItemId");

                    b.ToTable("ToDoItem");
                });

            modelBuilder.Entity("ToDoApp.Models.ToDoListItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Category");

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.Property<DateTime>("TimeCreated");

                    b.Property<int?>("UserItemId");

                    b.HasKey("Id");

                    b.HasIndex("UserItemId");

                    b.ToTable("ToDoListItem");
                });

            modelBuilder.Entity("ToDoApp.Models.UserItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ConfirmPassword");

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<string>("Hash");

                    b.Property<string>("LastName");

                    b.Property<string>("Password");

                    b.Property<int>("RoleId");

                    b.Property<string>("Salt");

                    b.Property<string>("Username");

                    b.HasKey("Id");

                    b.ToTable("UserItem");
                });

            modelBuilder.Entity("ToDoApp.Models.UserToDoListItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ToDoListItemId");

                    b.Property<int>("UserItemId");

                    b.HasKey("Id");

                    b.HasIndex("ToDoListItemId");

                    b.HasIndex("UserItemId");

                    b.ToTable("UserToDoListItem");
                });

            modelBuilder.Entity("ToDoApp.Models.ToDoItem", b =>
                {
                    b.HasOne("ToDoApp.Models.ToDoListItem", "ToDoListItem")
                        .WithMany("ToDoItems")
                        .HasForeignKey("ToDoListItemId");
                });

            modelBuilder.Entity("ToDoApp.Models.ToDoListItem", b =>
                {
                    b.HasOne("ToDoApp.Models.UserItem")
                        .WithMany("ToDoListItems")
                        .HasForeignKey("UserItemId");
                });

            modelBuilder.Entity("ToDoApp.Models.UserToDoListItem", b =>
                {
                    b.HasOne("ToDoApp.Models.ToDoListItem", "ToDoListItem")
                        .WithMany("UserToDoListItems")
                        .HasForeignKey("ToDoListItemId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ToDoApp.Models.UserItem", "UserItem")
                        .WithMany("UserToDoListItems")
                        .HasForeignKey("UserItemId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
